// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djlfpqlrdwvqsxxgaecv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqbGZwcWxyZHd2cXN4eGdhZWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NDM2OTIsImV4cCI6MjA1NTMxOTY5Mn0.glwlPju15LAAW3GpBHVyACuXZS-4PrpHNvJ7wUM8zW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);